/*
 * External_INT_Config.h
 *
 * Created: 2023/8/2 1:59:38 AM
 *  Author: Ahmed Adel
 */ 


#ifndef EXTERNAL_INT_CONFIG_H_
#define EXTERNAL_INT_CONFIG_H_


#define GLOBAL_INTERRUPT		GLOBAL_INTERRUPT_ENABLE

#define EXTERNAL_INT0_TRIGGER	INT0_TRIGGER_RISING_EDGE

#define EXTERNAL_INT1_TRIGGER	INT1_TRIGGER_RISING_EDGE

#define EXTERNAL_INT2_TRIGGER	INT2_TRIGGER_RISING_EDGE



#endif /* EXTERNAL_INT_CONFIG_H_ */